### PR TITLE
Updated recipe to 0.4.0

### PR DESCRIPTION
**Pull request by philippjfr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philippjfr** [comment]
@conda-forge-admin, please rerender

**Comment by philippjfr** [comment]
@ocefpaf Is there anything special I have to do to get it to find the latest holoviews 1.11.2? It went live on conda-forge about 26 minutes ago.

**Comment by philippjfr** [comment]
I also messed up a bit and accidentally pushed to master, does that break things badly?

**Comment by philippjfr** [comment]
Failed again because it couldn't resolve holoviews. Not sure what to do.

**Comment by jlstevens** [comment]
Just to say that locally I am picking up holoviews 1.11.2 from conda-forge. Maybe it will just take a little longer to propagate?

**Edit**: Seems pretty unlikely given how long ago the package became available...

**Comment by ocefpaf** [comment]
> @ocefpaf Is there anything special I have to do to get it to find the latest holoviews 1.11.2? It went live on conda-forge about 26 minutes ago.

It should be there already :-/

@msarahan are we having any problems with the channel?

**Comment by ocefpaf** [comment]
> I also messed up a bit and accidentally pushed to master, does that break things badly?

If the packages builds it will be uploaded, so avoid that to b/c we may accidentally upload a broken package.

**Comment by philippjfr** [comment]
>If the packages builds it will be uploaded, so avoid that to b/c we may accidentally upload a broken package.

I'll be more careful in future, in this case it most certainly would have failed so it won't have uploaded anything.

**Comment by philippjfr** [comment]
I'll periodically try to rerun this.

**Comment by philippjfr** [comment]
Okay, seems to be working now, thanks for the quick response @ocefpaf.

**Pull request merged**
